# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: get-label-list-for-pr-from-versions-file

description: >
  Get the label list for the pull request from `versions.json` file.

inputs:
  version:
    required: true    # [required]
    description: >
      The version to search for in the specified `versions.json` file.
  versions-file:
    default: 'versions.json'
    required: false
    description: >
      The path to the JSON file containing version data. Defaults to `versions.json`.
  working-directory:
    default: '${{ github.workspace }}'
    required: false
    description: >
      The directory from which to run commands or locate files. Defaults to `'\$\{\{ github.workspace \}\}'`.

outputs:
  PR_LABEL_LIST:
    value: ${{ steps.gllpr.outputs.PR_LABEL_LIST }}
    description: >
      A comma-separated list of PR labels.

runs:
  using: composite
  steps:
    - name: Get the Label List for the Pull Request from versions.json
      id: gllpr
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        VERSIONS_FILE="${{ inputs.versions-file }}"
        WORKING_DIRECTORY="${{ inputs.working-directory }}"

        JQ_FILTER="[.[] | map(select(.VERSION_COMPENDIUM == \"\"))] | add | .[].VERSION"
        JQ_FILE="${VERSIONS_FILE}"
        VERSION_LINES=($(jq -r "${JQ_FILTER}" "${JQ_FILE}" | tr -d '\r'))
        PR_LABEL_LIST="gettext"
        for VERSION_LINE in "${VERSION_LINES[@]}"; do
          if [[ "${VERSION}" == "${VERSION_LINE}" ]]; then
            PR_LABEL_LIST="${PR_LABEL_LIST},crowdin"
            break
          fi
        done

        echo "PR_LABEL_LIST=${PR_LABEL_LIST}" >> ${GITHUB_OUTPUT}
        echo "PR_LABEL_LIST:"
        echo "${PR_LABEL_LIST}"
