# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-pr-merged-to-l10n

on:
  workflow_call:
    inputs:
      RUNNER:
        type: string
        required: true  # [required]
        description: >
          The runner image for executing the job (e.g., 'ubuntu-latest').
      PR_TITLE:
        type: string
        required: true  # [required]
        description: >
          The title of the merged pull request.
      GETTEXT:
        type: string
        required: true  # [required]
        description: >
          Whether to trigger the `ci-gettext-update-po.yml` workflow to update `.po` files
          from `.pot` files (.e.g, 'true' or 'false').
      TMSCLI:
        type: string
        required: true  # [required]
        description: >
          Whether to trigger the `ci-tmscli-push-pot.yml` workflow to push `.pot` files to
          the translation management server (.e.g, 'true' or 'false').
      CALLER_JOB:
        type: string
        required: true  # [required]
        description: >
          The name of the caller job.
      ENABLE_JOB:
        type: string
        required: true  # [required]
        description: >
          Whether to enable the job (e.g., 'true' or 'false').
    secrets:
      ACTOR_GITHUB_TOKEN:
        required: true  # [required]
        description: >
          The personal access token of the GitHub actor.

jobs:
  pr-merged-to-l10n:
    if: ${{ inputs.ENABLE_JOB == 'true' }}
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Print Contexts/Inputs
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event.pull_request.base.ref = ${{ github.event.pull_request.base.ref }}"
          echo "github.event.pull_request.head.ref = ${{ github.event.pull_request.head.ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "[Inputs]"
          echo "inputs.RUNNER = ${{ inputs.RUNNER }}"
          echo "inputs.PR_TITLE = ${{ inputs.PR_TITLE }}"
          echo "inputs.GETTEXT = ${{ inputs.GETTEXT }}"
          echo "inputs.TMSCLI = ${{ inputs.TMSCLI }}"
          echo "inputs.CALLER_JOB = ${{ inputs.CALLER_JOB }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "[Secrets]"
          echo "secrets.ACTOR_GITHUB_TOKEN = ${{ secrets.ACTOR_GITHUB_TOKEN }}"

      - name: Get VERSION from the Pull Request Title
        id: gvprt
        uses: hwhsu1231/ci-sphinx/.github/actions/get-version-from-pull-request-title@main
        with:
          pr-title: ${{ inputs.PR_TITLE }}

      - name: Dispatch the 'pr-merged-to-l10n' event to the repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
          event-type: pr-merged-to-l10n
          client-payload: |
            {
              "TYPE" : "single",
              "VERSION" : "${{ steps.gvprt.outputs.VERSION }}",
              "LANGUAGE" : "all",
              "GETTEXT" : "${{ inputs.GETTEXT }}",
              "TMSCLI" : "${{ inputs.TMSCLI }}"
            }
