# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-deploy-gh-pages

on:
  workflow_call:
    inputs:
      RUNNER:
        required: true
        type: string
        description: Runner image for executing the job (e.g., 'ubuntu-latest').
      CHECKOUT:
        required: true
        type: string
        description: Git reference to be checked out (e.g., \$\{\{ github.ref \}\}).
      DEPLOY_BRANCH:
        required: true
        type: boolean
        description: xxx
      CALLER_JOB:
        required: true
        type: string
        description: Name of the job that triggers this workflow call.
      ENABLE_JOB:
        required: true
        type: boolean
        description: Whether to enable the job.
      ACTOR_NAME:
        required: true
        type: string
        description: Name of the GitHub actor.
      ACTOR_EMAIL:
        required: true
        type: string
        description: Login handle of the GitHub actor.
    secrets:
      ACTOR_GITHUB_TOKEN:
        required: true

jobs:
  merge-build-artifacts:
    if: ${{ inputs.ENABLE_JOB }}
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Print Contexts/Inputs/Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.workflow = ${{ github.workflow }}"
          echo "github.workflow_ref = ${{ github.workflow_ref }}"
          echo "github.run_id = ${{ github.run_id }}"
          echo "github.run_number = ${{ github.run_number }}"
          echo "github.run_attempt = ${{ github.run_attempt }}"
          echo "github.server_url = ${{ github.server_url }}"
          echo "github.repository = ${{ github.repository }}"
          echo "github.workspace = ${{ github.workspace }}"
          echo "[Inputs]"
          echo "inputs.RUNNER = ${{ inputs.RUNNER }}"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.DEPLOY_BRANCH = ${{ inputs.DEPLOY_BRANCH }}"
          echo "inputs.CALLER_JOB = ${{ inputs.CALLER_JOB }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "inputs.ACTOR_NAME = ${{ inputs.ACTOR_NAME }}"
          echo "inputs.ACTOR_EMAIL = ${{ inputs.ACTOR_EMAIL }}"
          echo "[Secrets]"
          echo "secrets.ACTOR_GITHUB_TOKEN = ${{ secrets.ACTOR_GITHUB_TOKEN }}"

      - name: Checkout to '${{ inputs.CHECKOUT }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT }}
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
          submodules: false

      - name: Download and Merge Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: 'out/${{ inputs.DEPLOY_BRANCH }}'
          merge-multiple: true
          github-token: ${{ secrets.ACTOR_GITHUB_TOKEN }}

      - name: Set up mutex for the '${{ inputs.DEPLOY_BRANCH }}' branch
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9
        with:
          branch: mutex/${{ inputs.DEPLOY_BRANCH }}
          repo-token: ${{ secrets.ACTOR_GITHUB_TOKEN }}

      - name: Deploy to the '${{ inputs.DEPLOY_BRANCH }}' branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ inputs.DEPLOY_BRANCH }}
          folder: 'out/${{ inputs.DEPLOY_BRANCH }}'
          target-folder: '.'
          single-commit: true
          clean: false
          git-config-name: ${{ inputs.ACTOR_NAME }}
          git-config-email: ${{ inputs.ACTOR_EMAIL }}
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}

  deploy-gh-pages:
    needs: [ 'merge-build-artifacts' ]
    if: ${{ inputs.ENABLE_JOB }}
    runs-on: ${{ inputs.RUNNER }}
    # Refer to: https://stackoverflow.com/a/76883315
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Print Contexts/Inputs/Secrets
        shell: bash
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.workflow = ${{ github.workflow }}"
          echo "github.workflow_ref = ${{ github.workflow_ref }}"
          echo "github.run_id = ${{ github.run_id }}"
          echo "github.run_number = ${{ github.run_number }}"
          echo "github.run_attempt = ${{ github.run_attempt }}"
          echo "github.server_url = ${{ github.server_url }}"
          echo "github.repository = ${{ github.repository }}"
          echo "github.workspace = ${{ github.workspace }}"
          echo "[Inputs]"
          echo "inputs.RUNNER = ${{ inputs.RUNNER }}"
          echo "inputs.CHECKOUT = ${{ inputs.CHECKOUT }}"
          echo "inputs.DEPLOY_BRANCH = ${{ inputs.DEPLOY_BRANCH }}"
          echo "inputs.CALLER_JOB = ${{ inputs.CALLER_JOB }}"
          echo "inputs.ENABLE_JOB = ${{ inputs.ENABLE_JOB }}"
          echo "inputs.ACTOR_NAME = ${{ inputs.ACTOR_NAME }}"
          echo "inputs.ACTOR_EMAIL = ${{ inputs.ACTOR_EMAIL }}"
          echo "[Secrets]"
          echo "secrets.ACTOR_GITHUB_TOKEN = ${{ secrets.ACTOR_GITHUB_TOKEN }}"

      - name: Checkout to 'refs/heads/${{ inputs.DEPLOY_BRANCH }}'
        uses: actions/checkout@v4
        with:
          ref: 'refs/heads/${{ inputs.DEPLOY_BRANCH }}'
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
          submodules: false

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'github-pages'
          path: '.'

      - name: Deploy Pages Artifact
        uses: actions/deploy-pages@v4
        with:
          artifact_name: 'github-pages'
          token: ${{ secrets.ACTOR_GITHUB_TOKEN }}
